graphite:
  image: hopsoft/graphite-statsd
  ports:
   - "80:80"
   - "2003:2003"
   - "8125:8125/udp"

# http://container-ip:15672 to view admin
rabbitmq:
  image: rabbitmq:3-management

redis:
  image: redis:redis

#~/D/cloud-native-workshop git:master ❯❯❯ docker run --name some-redis -d redis                                                                  ◼
# consul
#$ docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap -ui-dir /ui
consul:
  image: progrium/consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    - ""

logstash:
  image: pblittle/docker-logstash
  environment:
   - LOGSTASH_CONFIG_URL=https://raw.githubusercontent.com/mstine/statsd-graphite-demo/master/logstash.conf
  ports:
   - "10042:10042"
   - "9292:9292"
   - "9200:9200"
